name: Publish GitHub Release

on:
  push:
    tags:
      - '*'

permissions:
  packages: write
  contents: read

env:
  KIND_VERSION: 1.32
  KIND_MINOR: 2

jobs:
  build-and-publish-kind-image:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build with Docker
        run: docker build --build-arg VERSION=$KIND_VERSION --build-arg MINOR=$KIND_MINOR -f release/Dockerfile --output bins .

      - name: List built binaries
        run: ls -lah bins

      - name: Create tar
        run: |
          tar -czf criu-${{ github.ref_name}}-kind-v${KIND_VERSION}.${KIND_MINOR}-amd64.tar.gz -C bins .

      - name: Upload Release Asset
        uses: ncipollo/release-action@v1
        with:
          artifacts: "criu-${{ github.ref_name}}-kind-v${{ env.KIND_VERSION }}.${{ env.KIND_MINOR }}-amd64.tar.gz"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


