name: Publish GitHub Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  build-and-publish-kind-image:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Configure environment variables
        run: echo "RELEASE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: |
            linux/arm64
            linux/amd64

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: release/Dockerfile
          tags: |
            ghcr.io/castai/criu/criu:${{ env.RELEASE_TAG }}
            ghcr.io/castai/criu/criu:latest
          platforms: |
            linux/arm64
            linux/amd64
          outputs: |
            type=image,push=true
            type=local,dest=bins/

      - name: Create tar
        run: |
          for arch in amd64 arm64
          do
            tar czvf criu-${{ github.ref_name}}-linux-$arch.tar.gz -C bins/$arch criu
            sha256sum criu-${{ github.ref_name}}-linux-$arch.tar.gz >> SHA256SUMS
          done

      - name: Upload Release Asset
        uses: ncipollo/release-action@v1
        with:
          artifacts: "criu-${{ github.ref_name}}-linux-amd64.tar.gz,criu-${{ github.ref_name}}-linux-arm64.tar.gz,SHA256SUMS"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
